export const correctDriverStateName = (stateName: string): string => {
  const nameMapping: { [key: string]: string } = {
    firstName: "First Name",
    middleName: "Middle Name",
    lastName: "Last Name",
    dateOfBirth: "Date of Birth",
    email: "Email",
    mobile: "Mobile",
    nationality: "Nationality",
    currentAddress: "Current Address",
    permanentAddress: "Permanent Address",
    emergencyContactInformation: "Emergency Contact Information",
    licenseDetails: "License Details",
    employmentHistory: "Employment History",
    specialDrivingLicence: "Special Driving Licence",
    onboardingDocuments: "Onboarding Documents",
    visaStatus: "Visa Status",
    driverLicenseFront: "Driver License Front",
    driverLicenseBack: "Driver License Back",
    licenseHistory: "License History",
    policeVerification: "Police Verification",
    passportFront: "Passport Front",
    passportBack: "Passport Back",
    healthInsurance: "Health Insurance",
    driverCertificate: "Driver Certificate",
    fitness: "Fitness",
    drugTest: "Drug Test",
    houseNumber: "House Number",
    street: "Street",
    suburb: "Suburb",
    state: "State",
    country: "Country",
    pincode: "Pincode",
    contactName: "Contact Name",
    contactNumber: "Contact Number",
    relationship: "Relationship",
    licenseNumber: "License Number",
    licenseCardNumber: "License Card Number",
    licenceType: "Licence Type",
    dateOfIssue: "Date Of Issue",
    expiryDate: "Expiry Date",
    daysLeftForRenewal: "Days Left For Renewal",
    perviousEmployer: "Pervious Employer",
    yearsOfExperience: "Years Of Experience",
    reasonForLeaving: "Reason For Leaving",
    companyName: "Company Name",
    referenceContactName: "Reference Contact Name",
    referenceEmailId: "Reference Email Id",
    referenceContactNumber: "Reference Contact Number",
  };

  return nameMapping[stateName] || stateName;
};

export const correctCustomerStateName = (stateName: string): string => {
  const nameMapping: { [key: string]: string } = {
    companyName: "Company Name",
    tradingName: "Trading Name",
    abnNumber: "ABN Number",
    legalName: "Legal Name",
    websiteAddress: "Website Address",
    firstName: "First Name",
    lastName: "Last Name",
    designation: "Designation",
    companyAddress: "Company Address",
    street1: "Street 1",
    street2: "Street 2",
    suburb: "Suburb",
    state: "State",
    country: "Country",
    postCode: "Post Code",
    accountPayble: "Account Payble",
    contactPerson: "Contact Person",
    contactNumber: "Contact Number",
    accountsPaybleEmail: "Accounts Payable Email",
    accountReceivable: "Account Receivable",
    accountsReceivableEmail: "Accounts Receivable Email",
    opreations: "Opreations",
    opreationsEmail: "Operations Email",
    compliance: "Compliance",
    complianceEmail: "Compliance Email",
    admin: "Admin",
    adminEmail: "Admin Email",
    invoicePrefrences: "Invoice Preferences",
    invoiceCommunicationPrefrences: "Invoice Communication Preferences",
    companySuiteDetails: "Company Suite Details",
    directorEmailAddress: "Director Email Address",
    directorContactNumber: "Director Contact Number",
    payment: "Payment",
    accountName: "Account Name",
    bankName: "Bank Name",
    bsb: "BSB",
    accountNumber: "Account Number",
    paymentTerm: "Payment Term",
    warehouseLocation: "Warehouse Location",
    document: "Document",
  };

  return nameMapping[stateName] || stateName;
};
